on: [pull_request, push]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.10.4]
        otp: [22.2.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v1
        id: mix-cache # id to use in retrieve action
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Ensure Code is Formatted
        run: mix format --check-formatted
      - name: Compile for Tests
        run: MIX_ENV=test mix compile --warnings-as-errors
      - name: Run Tests
        run: mix test
      - name: Generate Release
        if: github.ref == 'refs/heads/master'
        run: mix release
      - name: Upload Artifacts
        if: github.ref == 'refs/heads/master'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: _build/prod/rel/bakeware/fika
          asset_name: fika
          tag: latest
          overwrite: true
